### ISSUE TITLE
issue getting token

### ISSUE THREAD

**Issue by sensnowy** [thboegel/homebridge-gardena-smart#1]
hi. 

i have been getting this issue lately

[7/9/2020, 22:04:36] [Gartensensor] getToken Successful login
[7/9/2020, 22:04:36] [Gartensensor] Cannot get Token {
  options: {
    method: 'POST',
    uri: 'https://smart.gardena.com/v1/auth/token',
    body: { data: [Object] },
    json: true
  }
} 400 undefined
(node:2135) UnhandledPromiseRejectionWarning: StatusCodeError: 400 - {"errors":[{"code":"simultaneous.logins","status":400,"title":"Bad request","detail":"Simultaneous logins detected."}]}
    at new StatusCodeError (/usr/local/lib/node_modules/homebridge-gardena-smart/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-gardena-smart/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-gardena-smart/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-gardena-smart/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-gardena-smart/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-gardena-smart/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
(node:2135) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 31)
[7/9/2020, 22:04:36] [Gartensensor] getToken Successful login

**Comment by thboegel** [comment]
Hi, thanks for letting me know. I was apparently calling the getToken method twice. The problem should now be fixed in the current version 0.0.8. Otherwise, please let me know.
